changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security and hardening
      labels:
        - security
    - title: Features and integrations
      labels:
        - enhancement
        - integration
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
