export {
  BROWSER_AUTOMATION_ACTION_CATALOG,
  BROWSER_AUTOMATION_ACTION_EFFECTS,
  BROWSER_AUTOMATION_ACTIONS,
  BROWSER_AUTOMATION_CATEGORIES,
  BROWSER_AUTOMATION_CATEGORY_CATALOG,
  BROWSER_AUTOMATION_EFFECTS,
  BROWSER_AUTOMATION_SAFE_ACTIONS,
  browserAutomationEffectForAction
} from "./catalog.js";
export { createGovernedBrowserAutomation, BrowserAutomationError } from "./adapter.js";
export {
  createGovernedPlaywrightBackend,
  GOVERNED_ENGINE_HANDLER_ACTIONS,
  GOVERNED_ENGINE_REQUIRED_SERVICES,
  GOVERNED_ENGINE_UNSUPPORTED_ACTIONS
} from "./playwright-backend.js";
